### ISSUE TITLE
How do you use deformable_attn.py?

### ISSUE THREAD

**Issue by DCSong** [jiangxiluning/Deformable-DETR#1]
Thanks for your great work.
I'm wondering how does deformable_attn.py work. Dose it not complete entirely?
And do you reference to the realization of https://github.com/Windaway/Deformable-Attention-for-Deformable-DETR/blob/main/DFMAtt.py?
Thank you!

**Comment by jiangxiluning** [comment]
@DCSong I do follow the implementation of https://github.com/Windaway/Deformable-Attention-for-Deformable-DETR/blob/main/DFMAtt.py. I will add thanks to his work. Moreover, my implementation is a multi-scale version. And I will finish the coco2017 training procedure with Deformable-Detr and release the whole project and mode. Thanks.

**Comment by DCSong** [comment]
Thanks for your reply. Looking forward your work.
